# Hackathon Starter Kit - Main Orchestration
# Battle-tested full-stack setup with public URLs
# 
# Quick Start:
#   docker compose up              # Start everything
#   docker compose down            # Stop everything  
#   docker compose up --build      # Rebuild and start
#
# Your URLs:
#   https://hackathon.b28.dev/app  # Frontend (public)
#   https://hackathon.b28.dev/api  # Backend API (public)
#   http://localhost:8080          # Traefik dashboard (local)

name: hackathon-starter-kit

# Service configurations
# Each service is modular for easy customization
include:
  - path: ./compose/frontend.yml    # Astro frontend with hot reload
  - path: ./compose/backend.yml     # FastAPI backend with auto-docs
  - path: ./compose/traefik.yml     # Reverse proxy with service discovery
  - path: ./compose/tunnel.yml      # Cloudflare tunnel for public HTTPS

# Shared infrastructure
networks:
  hackathon:
    name: hackathon-network
    driver: bridge

volumes:
  traefik-ssl:
    name: hackathon-traefik-ssl
    
# Reusable configurations
x-common-env: &common-env
  NODE_ENV: ${NODE_ENV:-development}
  LOG_LEVEL: ${LOG_LEVEL:-info}
  TZ: ${TZ:-UTC}

x-restart-policy: &restart-policy
  restart: unless-stopped

# Optional: Disable tunnel for local-only development
# Comment out the tunnel include above and uncomment below:
# 
# x-local-only: &local-urls
#   Frontend: http://localhost/app
#   Backend:  http://localhost/api
#   Dashboard: http://localhost:8080
