# Backend Service - FastAPI
# Hot reload with uvicorn --reload
# External database URL only (no local DB containers)

services:
  backend:
    build:
      context: ../services/backend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    
    container_name: hackbase-backend
    
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    
    volumes:
      # Hot reload - mount source code
      - ../services/backend:/app
    
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV:-development}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CORS_ORIGINS=http://localhost:${FRONTEND_PORT:-3000},http://localhost
      - API_KEY=${API_KEY:-}
    
    networks:
      - hackathon
    
    labels:
      # Traefik routing for API
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.priority=100
      - traefik.http.routers.backend.middlewares=api-stripprefix
      - traefik.http.services.backend.loadbalancer.server.port=8000
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
    
    restart: unless-stopped
