# Frontend Service - Astro/Vite
# Hot reload enabled for development
# Production builds handled by Dagger pipeline

services:
  frontend:
    build:
      context: ../services/frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    
    container_name: hackbase-frontend
    
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    
    volumes:
      # Hot reload - mount source code
      - ../services/frontend:/app
      - /app/node_modules
      - /app/.astro
    
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-8000}
      - VITE_PUBLIC_URL=${DOMAIN:-localhost}
    
    networks:
      - hackathon
    
    labels:
      # Traefik routing - serve at root, but with lower priority than API
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`hackathon.b28.dev`) || Host(`localhost`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.priority=1
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    
    restart: unless-stopped
