# Traefik Reverse Proxy Service
# This handles all routing and SSL termination for our hackathon app

services:
  traefik:
    image: traefik:v3.0
    container_name: hackathon-traefik
    restart: unless-stopped
    
    # Ports - expose HTTP, HTTPS, and dashboard
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS  
      - "8080:8080"   # Traefik dashboard
    
    # Volumes - mount config and Docker socket
    volumes:
      - ../traefik.yml:/etc/traefik/traefik.yml:ro  # Main config
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Docker API
      - traefik-ssl:/letsencrypt  # SSL certificate storage
    
    # Network - connect to your existing shared network
    networks:
      - hackathon
    
    # Labels for Traefik dashboard routing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
    
    # Environment variables
    environment:
      - TRAEFIK_LOG_LEVEL=INFO

# Networks - no need to declare here, using the one from main compose

# Volumes - persistent storage for SSL certificates
volumes:
  traefik-ssl:
    name: hackathon-traefik-ssl
