# Cloudflare Tunnel Service
# Exposes your local app to the internet via hackathon.b28.dev

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: hackathon-tunnel
    restart: unless-stopped
    
    # Command to run the tunnel with container config
    command: tunnel --config /home/nonroot/.cloudflared/container-config.yml run
    
    # Mount your Cloudflare config and credentials
    volumes:
      - ~/.cloudflared:/home/nonroot/.cloudflared:ro
    
    # Connect to the same network as your app
    networks:
      - hackathon
    
    # Depend on Traefik being ready
    depends_on:
      - traefik
    
    # Environment variables (optional)
    environment:
      - TUNNEL_METRICS=0.0.0.0:2000  # Metrics endpoint
    
    # Health check
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Labels for Traefik (if you want to expose tunnel metrics)
    labels:
      - "traefik.enable=false"  # Don't route tunnel service itself
